name: Deploy to Netlify

on:
  push:
    branches:
    - github-action-test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Set Node.js
      uses: actions/setup-node@master
      with:
        node-version: 12.13.1
        
    - name: Install Gatsby
      run: npm i -g gatsby
      
    - name: Install dependencies
      run: npm install
    
    - name: Run linter
      uses: stefanoeb/eslint-action@1.0.0
    
    - name: Run tests
      run: npm run test:e2e:ci
    
    - name: Build app
      run: npm run build
    
    - name: Lighthouse Audit
      uses: jakejarvis/lighthouse-action@v0.3.2
      
    - name: Deploy to Netlify
      if: job.status == 'success'
      run: curl -X POST -d '' https://api.netlify.com/build_hooks/5ba3c8da1f12b70cbbcaa1a3 && curl -X POST -d {} https://api.netlify.com/build_hooks/5daf5f3d31ede3a743f5bebc
