name: Deploy to Netlify

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: npm install, lint, test and build
      run: |
        npm i -g gatsby
        npm ci
        npm run lint
        npm test:e2e:ci
        npm run build
      env:
        CI: true
    - name: Lighthouse Audit
      uses: jakejarvis/lighthouse-action@v0.3.2
    - name: Deploy to Netlify
      if: job.status == 'success'
      run: curl -X POST -d '' https://api.netlify.com/build_hooks/5ba3c8da1f12b70cbbcaa1a3 && curl -X POST -d {} https://api.netlify.com/build_hooks/5daf5f3d31ede3a743f5bebc
