name: Lint, E2E and Deploy

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: npm Cache Folder
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Set Node.js
      uses: actions/setup-node@master
      with:
        node-version: 14.15.0

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Run E2E tests
      uses: cypress-io/github-action@v2
      env:
        CI: true
        IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        install: false # we have already installed all dependencies above
        record: true
        start: npm start
        wait-on: 'http://localhost:8000'
        wait-on-timeout: 1800
        browser: chrome
        headless: true

    - name: Deploy to Netlify
      if: job.status == 'success'
      run: curl -X POST -d '' ${{secrets.NETLIFY_WEBHOOK_DE}} && curl -X POST -d {} ${{secrets.NETLIFY_WEBHOOK_COM}}

    - name: Send notification mail
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
        # user credentials
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        # email subject
        subject: GitHub Action - ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        # email body as text
        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
        to: michael.hoffmann@mokkapps.de
        from: ${{secrets.MAIL_USERNAME}}

